global using ETBDApp.Data;
global using ETBDApp.Data.Entities;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.Data.SqlClient;
global using Action = ETBDApp.Data.Entities.Action;
global using ETBDApp.Data.Entities.Roles;